---
#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g., /blog
url: "https://sagewoodard.github.io" # Your GitHub Pages URL

title: "Machine Learning Applications | Sage Woodard"
description: "Showcasing projects in machine learning, data science, and AI."

favicon: /images/favicon.png

author:
  name: "Sage Woodard"
  email: "sagewoodard@ksu.edu"

#-------------------------------
# Build Settings
safe: true
markdown: kramdown
highlighter: rouge # Ensure syntax highlighting works
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed # Optional: Adds an RSS feed
  - jekyll-seo-tag # Optional: Adds SEO tags
  - kramdown-parser-gfm # Ensure compatibility with GitHub Flavored Markdown

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages
  - gan-vs-sdm-project # Add this to allow direct access to project files

sass:
  sass_dir: _sass
  style: compressed

#-------------------------------
# Theme-Specific Settings

# Navbar links
navbar:
  - name: "Home"
    href: "/"
  - name: "Projects"
    href: "/projects/"
  - name: "About"
    href: "/about/"
  - name: "Contact"
    href: "/contact/"

# Footer links
footer_links:
  - name: "GitHub"
    href: "https://github.com/sagewoodard"
  - name: "LinkedIn"
    href: "https://linkedin.com/in/sagewoodard"
  - name: "Email"
    href: "mailto:sagewoodard@ksu.edu"

# Social media links
social:
  github: "https://github.com/sagewoodard"
  linkedin: "https://linkedin.com/in/sagewoodard"
  email: "sagewoodard@ksu.edu"
---

