---
#-------------------------------
# Site Settings
title: Machine Learning and Data Science Applications | Sage Woodard
logo: # You can add your own logo. For example '/images/logo.png'.
description: Developing machine learning applications that transform data into actionable insights, solve complex problems, and drive meaningful change.

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Projects"
      url: "/projects/"
    - title: "Contact"
      url: "/contact/"

#-------------------------------
# Author Settings
author:
  name: Sage Woodard
  avatar: "/images/logo.png" # Replace with your avatar image

#-------------------------------
# Hero Settings
hero:
  title: Sage Woodard
  description: Developing machine learning applications that transform data into actionable insights, solve complex problems, and drive meaningful change.
  image: "/images/background.jpg" # Replace with your background image

#-------------------------------
# Contact Settings
contact:
  email: sagewoodard@ksu.edu
  linkedin: https://linkedin.com/in/sagewoodard
  github: https://github.com/sagewoodard
  description: Feel free to reach out via email, LinkedIn, or GitHub.

#-------------------------------
# Footer Section
social:
  - {
      icon: "fa-brands fa-linkedin",
      name: "LinkedIn",
      link: "https://linkedin.com/in/sagewoodard",
    }
  - {
      icon: "fa-brands fa-github",
      name: "GitHub",
      link: "https://github.com/sagewoodard",
    }
  - {
      icon: "fa-solid fa-envelope",
      name: "Email",
      link: "mailto:sagewoodard@ksu.edu",
    }

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your Disqus identifier if you want to enable comments. Leave blank to disable.

#-------------------------------
# Google Analytics
google-analytics: # Add your Google Analytics identifier if needed.

#-------------------------------
# Newsletter
mailchimp: # To enable the Mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your Mailchimp form identifier if needed.
mailchimp-button-text: Join
