# -*- coding: utf-8 -*-
"""FID s-score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIyIUtYqWvQLyiQoxTWNZMBiUvFw8XeS
"""

import matplotlib.pyplot as plt

# Example FID scores
fid_gan = 1846.365750809347
fid_sd = 165.73935229494703

# Compute s-values
s_difference = fid_gan - fid_sd
s_ratio = fid_gan / fid_sd

# Print Results
print(f"FID (GAN): {fid_gan}")
print(f"FID (Stable Diffusion): {fid_sd}")
print(f"s-value (Difference): {s_difference}")
print(f"s-value (Ratio): {s_ratio}")

# Plot Results
models = ['GAN', 'Stable Diffusion']
fid_scores = [fid_gan, fid_sd]

plt.bar(models, fid_scores, color=['blue', 'green'])
plt.ylabel('FID Score')
plt.title('FID Scores Comparison')
plt.show()